"use strict";
const fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const version=require("../../package.json").version;
const files=["circular.jsxinc","outlines.jsxinc","geometry.jsxinc","host.jsxinc","settings.jsxinc","ui.jsxinc"];
const built="// Shape-to-Stroke v"+version+" (experimental) — Pedro Mafra\n// MIT License. Standalone ExtendScript; generated by experimental/shape-to-stroke/build.js.\n// Usage and limitations: https://github.com/pdrmafra/after-effects-scripts\n(function () {\n"+files.map(f=>fs.readFileSync(path.join(__dirname,f),"utf8")).join("\n")+"\n}());\n";
new vm.Script(built,{filename:"Shape-to-Stroke.jsx"});
// Test comps carry the collection version so older demo comps stay distinguishable.
if(!fs.readFileSync(path.join(__dirname,"fixtures.jsxinc"),"utf8").includes('"Shape to Stroke v'+version+' '))throw new Error("fixtures.jsxinc comp names do not use version "+version+".");
const target=path.join(__dirname,"Shape-to-Stroke.jsx");
if(process.argv.includes("--check")) {
  if(fs.readFileSync(target,"utf8")!==built) throw new Error("Stale Shape-to-Stroke build. Run npm run build.");
} else fs.writeFileSync(target,built);
console.log((process.argv.includes("--check") ? "Checked" : "Built")+" Shape-to-Stroke");
