// Keyframe-Tools v0.3.0-beta.1 — Pedro Mafra
// MIT License. Standalone ExtendScript; generated by tools/build.js.
// Usage and limitations: https://github.com/pdrmafra/after-effects-scripts
(function (thisObj) {
// Shared ES3-compatible source. Build embeds it in each standalone script.
var PedroAE = (function () {
    var EPS = 0.000001;

    function fail(message) { throw new Error(message); }
    function clone(value) {
        if (!(value instanceof Array)) return value;
        var result = [];
        for (var i = 0; i < value.length; i++) result.push(clone(value[i]));
        return result;
    }
    function equal(a, b) {
        if (typeof a === "number" && typeof b === "number") return Math.abs(a - b) < EPS;
        if (a instanceof Array && b instanceof Array) {
            if (a.length !== b.length) return false;
            for (var i = 0; i < a.length; i++) if (!equal(a[i], b[i])) return false;
            return true;
        }
        return a === b;
    }
    function comp() {
        var item = app.project && app.project.activeItem;
        if (!(item instanceof CompItem)) fail("Open a composition first.");
        return item;
    }
    function selectedLayers(c) {
        var layers = c.selectedLayers;
        if (!layers.length) fail("Select at least one layer.");
        return layers;
    }
    function undo(name, action) {
        app.beginUndoGroup(name);
        try { return action(); } finally { app.endUndoGroup(); }
    }
    function run(name, action) {
        try { action(); } catch (error) { alert(name + ":\n" + error.toString()); }
    }
    function walk(group, visit) {
        if (group.propertyType === PropertyType.PROPERTY) { visit(group); return; }
        for (var i = 1; i <= group.numProperties; i++) walk(group.property(i), visit);
    }
    function hasExpression(p) { return p.canSetExpression && p.expression !== ""; }
    function spatial(p) {
        return p.propertyValueType === PropertyValueType.TwoD_SPATIAL || p.propertyValueType === PropertyValueType.ThreeD_SPATIAL;
    }
    function supported(p) {
        var t = p.propertyValueType;
        return t === PropertyValueType.OneD || t === PropertyValueType.TwoD ||
            t === PropertyValueType.ThreeD || t === PropertyValueType.COLOR ||
            t === PropertyValueType.TwoD_SPATIAL || t === PropertyValueType.ThreeD_SPATIAL ||
            t === PropertyValueType.SHAPE || t === PropertyValueType.TEXT_DOCUMENT;
    }
    function easeData(ease) {
        var data = [];
        for (var i = 0; i < ease.length; i++) data.push([ease[i].speed, ease[i].influence]);
        return data;
    }
    function easeObjects(data) {
        var ease = [];
        for (var i = 0; i < data.length; i++) ease.push(new KeyframeEase(data[i][0], data[i][1]));
        return ease;
    }
    function snapshot(p) {
        var data = { property: p, keys: [] };
        if (!p.numKeys) { data.value = clone(p.value); return data; }
        for (var i = 1; i <= p.numKeys; i++) {
            var k = {
                time: p.keyTime(i), value: clone(p.keyValue(i)), selected: p.keySelected(i),
                inType: p.keyInInterpolationType(i), outType: p.keyOutInterpolationType(i),
                inEase: easeData(p.keyInTemporalEase(i)), outEase: easeData(p.keyOutTemporalEase(i)),
                continuous: p.keyTemporalContinuous(i), auto: p.keyTemporalAutoBezier(i)
            };
            if (spatial(p)) {
                k.inTangent = clone(p.keyInSpatialTangent(i));
                k.outTangent = clone(p.keyOutSpatialTangent(i));
                k.spatialContinuous = p.keySpatialContinuous(i);
                k.spatialAuto = p.keySpatialAutoBezier(i);
                k.roving = p.keyRoving(i);
            }
            // Keyframe labels were added in AE 22.6. Never suppress a failed copy.
            if (typeof p.keyLabel === "function") k.label = p.keyLabel(i);
            data.keys.push(k);
        }
        return data;
    }
    function clearKeys(p) { for (var i = p.numKeys; i >= 1; i--) p.removeKey(i); }
    function write(p, data) {
        var easing = [], supportsEase = p.isInterpolationTypeValid(KeyframeInterpolationType.BEZIER);
        // Source Text is HOLD-only and reports zero influence (invalid for KeyframeEase).
        // Prepare all valid ease objects before deleting any existing keys.
        for (var e = 0; e < data.keys.length; e++) {
            var original = data.keys[e];
            if (supportsEase && (original.inType !== KeyframeInterpolationType.HOLD || original.outType !== KeyframeInterpolationType.HOLD)) {
                easing[e] = [easeObjects(original.inEase), easeObjects(original.outEase)];
            }
        }
        clearKeys(p);
        if (!data.keys.length) { p.setValue(clone(data.value)); return; }
        var i, k;
        // Create the complete sequence before assigning neighbor-dependent flags.
        for (i = 0; i < data.keys.length; i++) {
            k = data.keys[i];
            var index = p.addKey(k.time);
            p.setValueAtKey(index, clone(k.value));
        }
        for (i = 0; i < data.keys.length; i++) {
            k = data.keys[i];
            p.setTemporalAutoBezierAtKey(i + 1, false);
            p.setTemporalContinuousAtKey(i + 1, false);
            if (easing[i]) p.setTemporalEaseAtKey(i + 1, easing[i][0], easing[i][1]);
            // Ease setters can change interpolation: restore interpolation AFTER ease.
            p.setInterpolationTypeAtKey(i + 1, k.inType, k.outType);
            if (spatial(p)) {
                p.setSpatialAutoBezierAtKey(i + 1, false);
                p.setSpatialContinuousAtKey(i + 1, false);
                p.setSpatialTangentsAtKey(i + 1, k.inTangent, k.outTangent);
                p.setSpatialContinuousAtKey(i + 1, k.spatialContinuous);
                p.setSpatialAutoBezierAtKey(i + 1, k.spatialAuto);
            }
            p.setTemporalContinuousAtKey(i + 1, k.continuous);
            p.setTemporalAutoBezierAtKey(i + 1, k.auto);
            if (k.label !== undefined) p.setLabelAtKey(i + 1, k.label);
            p.setSelectedAtKey(i + 1, k.selected);
        }
        if (spatial(p)) {
            for (i = 0; i < data.keys.length; i++) p.setRovingAtKey(i + 1, data.keys[i].roving);
        }
    }
    function verify(p, data) {
        var actual = snapshot(p);
        if (actual.keys.length !== data.keys.length) fail("Key count changed while copying " + p.name + ".");
        if (!data.keys.length) {
            if (!equal(actual.value, data.value)) fail("Static value copy failed: " + p.name);
            return;
        }
        for (var i = 0; i < data.keys.length; i++) {
            var expected = data.keys[i], copied = actual.keys[i];
            for (var field in expected) {
                if (expected.hasOwnProperty(field) && !equal(expected[field], copied[field])) {
                    fail("Key copy verification failed: " + p.name + " key " + (i + 1) + " / " + field);
                }
            }
        }
    }
    function restoreAll(plans, count, error) {
        var failures = [];
        for (var i = count - 1; i >= 0; i--) {
            try { write(plans[i].property, plans[i].before); }
            catch (restoreError) { failures.push(restoreError.toString()); }
        }
        if (failures.length) fail(error.toString() + "\nRecovery incomplete. Use Undo immediately.\n" + failures.join("\n"));
        throw error;
    }
    function keyProperties(c, allKeys) {
        var result = [], selected = c.selectedProperties;
        for (var i = 0; i < selected.length; i++) {
            walk(selected[i], function (p) {
                if (!p.numKeys || (!allKeys && (!p.selectedKeys || !p.selectedKeys.length))) return;
                for (var j = 0; j < result.length; j++) if (result[j] === p) return;
                var layer = p.propertyGroup(p.propertyDepth);
                if (layer.locked) fail("Unlock layer: " + layer.name);
                if (!supported(p)) fail("Unsupported property: " + p.name);
                if (hasExpression(p)) fail("Remove expressions first: " + p.name);
                var before = snapshot(p);
                for (j = 0; j < before.keys.length; j++) {
                    var k = before.keys[j];
                    if (k.roving || k.auto || k.continuous) {
                        fail("Disable roving / temporal auto-Bezier / temporal continuous first: " + p.name);
                    }
                }
                result.push(p);
            });
        }
        if (!result.length) fail("Select animated properties and keyframes first.");
        return result;
    }
    function frameInterval(value) {
        var number = Number(value);
        if (!isFinite(number) || number <= 0 || Math.floor(number) !== number) fail("Enter a positive whole number of frames.");
        return number;
    }
    function applyPlans(name, plans) {
        return undo(name, function () {
            var count = 0;
            try {
                for (var i = 0; i < plans.length; i++) {
                    count = i + 1;
                    write(plans[i].property, plans[i].after);
                }
            } catch (error) { restoreAll(plans, count, error); }
            return plans.length;
        });
    }
    function space(c, frames, atCurrentTime, allKeys) {
        frames = frameInterval(frames);
        var properties = keyProperties(c, allKeys), plans = [];
        for (var i = 0; i < properties.length; i++) {
            var p = properties[i], before = snapshot(p), after = { keys: [] }, chosen = [];
            for (var j = 0; j < before.keys.length; j++) {
                var key = {}, original = before.keys[j];
                for (var field in original) if (original.hasOwnProperty(field)) key[field] = original[field];
                after.keys.push(key);
                if (allKeys || key.selected) chosen.push(key);
            }
            if (!chosen.length || (chosen.length === 1 && !atCurrentTime)) continue;
            var start = atCurrentTime ? c.time : chosen[0].time;
            for (j = 0; j < chosen.length; j++) chosen[j].time = start + j * frames * c.frameDuration;
            after.keys.sort(function (a, b) { return a.time - b.time; });
            for (j = 1; j < after.keys.length; j++) {
                if (Math.abs(after.keys[j].time - after.keys[j - 1].time) < EPS) {
                    fail("Spacing cancelled: a key would overwrite another key on " + p.name + ".");
                }
            }
            plans.push({ property: p, before: before, after: after });
        }
        if (!plans.length) fail("Select at least two keys, or choose Current Time to move a single key.");
        return applyPlans("Spacing Keyframes", plans);
    }
    function sampledKey(p, time, value, hold) {
        var count = p.keyInTemporalEase(1).length, easing = [], i;
        for (i = 0; i < count; i++) easing.push([0, 33.333333]);
        var type = hold || !p.isInterpolationTypeValid(KeyframeInterpolationType.LINEAR) ? KeyframeInterpolationType.HOLD : KeyframeInterpolationType.LINEAR;
        var k = { time: time, value: clone(value), selected: true,
            inType: type, outType: type, inEase: easing, outEase: easing,
            continuous: false, auto: false };
        if (spatial(p)) {
            var tangent = [];
            for (i = 0; i < value.length; i++) tangent.push(0);
            k.inTangent = tangent; k.outTangent = clone(tangent);
            k.spatialContinuous = false; k.spatialAuto = false; k.roving = false;
        }
        if (typeof p.keyLabel === "function") k.label = 0;
        k.sample = true;
        return k;
    }
    // A spatial segment is the cubic Bezier value, value+outTangent, next+inTangent, next.
    // Splitting it at the samples (de Casteljau) keeps the original motion path. Without this,
    // the bounding keys keep handles sized for the whole segment and loop around close samples.
    function lerp(a, b, t) { var r = []; for (var i = 0; i < a.length; i++) r.push(a[i] + (b[i] - a[i]) * t); return r; }
    function offset(a, b, sign) { var r = []; for (var i = 0; i < a.length; i++) r.push(a[i] + sign * b[i]); return r; }
    function distance(a, b) { var s = 0; for (var i = 0; i < a.length; i++) s += (a[i] - b[i]) * (a[i] - b[i]); return Math.sqrt(s); }
    function split(c, u) {
        var a = lerp(c[0], c[1], u), b = lerp(c[1], c[2], u), d = lerp(c[2], c[3], u), e = lerp(a, b, u), f = lerp(b, d, u), m = lerp(e, f, u);
        return [[c[0], a, e, m], [m, f, d, c[3]]];
    }
    function curveParameter(c, point, from) {
        var best = from, bestDistance = Infinity, steps = 128, step = (1 - from) / steps, i, j, u, d;
        for (i = 0; i <= steps; i++) {
            u = from + i * step; d = distance(split(c, u)[0][3], point);
            if (d < bestDistance) { bestDistance = d; best = u; }
        }
        for (i = 0; i < 40; i++) {
            step /= 2;
            for (j = -1; j <= 1; j += 2) {
                u = Math.min(1, Math.max(from, best + j * step)); d = distance(split(c, u)[0][3], point);
                if (d < bestDistance) { bestDistance = d; best = u; }
            }
        }
        return { u: best, error: bestDistance };
    }
    function subdivideSpatial(keys) {
        for (var i = 0; i < keys.length; i++) {
            if (keys[i].sample) continue;
            var j = i + 1;
            while (j < keys.length && keys[j].sample) j++;
            if (j >= keys.length || j === i + 1 || keys[i].outType === KeyframeInterpolationType.HOLD) continue;
            var a = keys[i], b = keys[j], curve = [a.value, offset(a.value, a.outTangent, 1), offset(b.value, b.inTangent, 1), b.value];
            var tolerance = Math.max(0.01, 0.00001 * (distance(curve[0], curve[1]) + distance(curve[1], curve[2]) + distance(curve[2], curve[3])));
            var found = [], from = 0, s;
            for (s = i + 1; s < j; s++) {
                var hit = curveParameter(curve, keys[s].value, from);
                if (hit.error > tolerance) break;
                found.push(hit.u); from = hit.u;
            }
            // A sample off this curve is unexpected: keep straight sample handles, as before.
            if (found.length !== j - i - 1) continue;
            var rest = curve, start = 0, previous = a;
            for (s = 0; s < found.length; s++) {
                var parts = split(rest, start < 1 ? (found[s] - start) / (1 - start) : 0), sample = keys[i + 1 + s];
                previous.outTangent = offset(parts[0][1], parts[0][0], -1);
                sample.inTangent = offset(parts[0][2], parts[0][3], -1);
                sample.outTangent = offset(parts[1][1], parts[1][0], -1);
                sample.spatialContinuous = true;
                rest = parts[1]; start = found[s]; previous = sample;
            }
            b.inTangent = offset(rest[2], rest[3], -1);
        }
    }
    function step(c, frames, hold) {
        frames = frameInterval(frames);
        var properties = keyProperties(c, false), plans = [], total = 0;
        for (var i = 0; i < properties.length; i++) {
            var p = properties[i], before = snapshot(p), after = { keys: [] }, selected = [];
            for (var j = 0; j < before.keys.length; j++) {
                var key = {}, original = before.keys[j];
                for (var field in original) if (original.hasOwnProperty(field)) key[field] = original[field];
                after.keys.push(key);
                if (key.selected) selected.push(key.time);
            }
            if (selected.length < 2) continue;
            var added = 0;
            for (j = 0; j < selected.length - 1; j++) {
                var start = selected[j], end = selected[j + 1], interval = frames * c.frameDuration;
                // All values come from the untouched original curve, not inserted keys.
                for (var n = 1; start + n * interval < end - EPS; n++) {
                    var time = start + n * interval, exists = false;
                    for (var k = 0; k < before.keys.length; k++) {
                        if (Math.abs(before.keys[k].time - time) < EPS) { exists = true; break; }
                    }
                    if (exists) continue;
                    if (++total > 10000) fail("Cancelled: more than 10,000 new keys. Use a larger interval.");
                    after.keys.push(sampledKey(p, time, p.valueAtTime(time, true), hold));
                    added++;
                }
                if (hold) {
                    for (k = 0; k < after.keys.length; k++) {
                        if (after.keys[k].time >= start - EPS && after.keys[k].time < end - EPS) {
                            after.keys[k].inType = KeyframeInterpolationType.HOLD;
                            after.keys[k].outType = KeyframeInterpolationType.HOLD;
                        }
                    }
                }
            }
            if (!added && !hold) continue;
            after.keys.sort(function (a, b) { return a.time - b.time; });
            if (!hold && spatial(p)) subdivideSpatial(after.keys);
            for (j = 0; j < after.keys.length; j++) delete after.keys[j].sample;
            plans.push({ property: p, before: before, after: after });
        }
        if (!plans.length) fail("No samples to insert. Select at least two keys and check the interval.");
        applyPlans("Stepped Keyframes", plans);
        return total;
    }
    function copyKeys(keys) {
        var result = [];
        for (var i = 0; i < keys.length; i++) {
            var key = {}, original = keys[i];
            for (var field in original) if (original.hasOwnProperty(field)) key[field] = original[field];
            result.push(key);
        }
        return result;
    }
    // Keeps every Nth selected key (the 1st, 1+N-th, 1+2N-th...) and removes the selected keys
    // between them. The last selected key always stays; unselected keys are never removed.
    function keepEvery(c, every) {
        var n = Number(every);
        if (!isFinite(n) || n < 2 || Math.floor(n) !== n) fail("Enter a whole number of keys, 2 or more (2 keeps every other key).");
        var properties = keyProperties(c, false), plans = [], removed = 0, i, j;
        for (i = 0; i < properties.length; i++) {
            var p = properties[i], before = snapshot(p), selected = [];
            for (j = 0; j < before.keys.length; j++) if (before.keys[j].selected) selected.push(j);
            var drop = {}, count = 0;
            for (j = 1; j < selected.length - 1; j++) if (j % n) { drop[selected[j]] = true; count++; }
            if (!count) continue;
            var kept = [], all = copyKeys(before.keys);
            for (j = 0; j < all.length; j++) if (!drop[j]) kept.push(all[j]);
            plans.push({ property: p, before: before, after: { keys: kept } });
            removed += count;
        }
        if (!plans.length) fail("Nothing to remove. Select at least three keys on a property.");
        applyPlans("Keep Every N Keys", plans);
        return removed;
    }
    // Moves each layer's selected keys together, keeping their spacing: the earliest lands on
    // the layer's in point, or the latest on its last visible frame (out point minus one frame).
    function keysToLayer(c, edge) {
        if (edge !== "in" && edge !== "out") fail("Edge must be in or out.");
        var properties = keyProperties(c, false), groups = [], plans = [], moved = 0, i, j, k;
        for (i = 0; i < properties.length; i++) {
            var p = properties[i], layer = p.propertyGroup(p.propertyDepth), group = null, before = snapshot(p);
            for (j = 0; j < groups.length; j++) if (groups[j].layer === layer) group = groups[j];
            if (!group) { group = { layer: layer, items: [], first: Infinity, last: -Infinity }; groups.push(group); }
            for (j = 0; j < before.keys.length; j++) if (before.keys[j].selected) {
                group.first = Math.min(group.first, before.keys[j].time);
                group.last = Math.max(group.last, before.keys[j].time);
            }
            group.items.push({ property: p, before: before });
        }
        for (i = 0; i < groups.length; i++) {
            var g = groups[i], shift = edge === "in" ? g.layer.inPoint - g.first : g.layer.outPoint - c.frameDuration - g.last;
            if (Math.abs(shift) < EPS) continue;
            for (j = 0; j < g.items.length; j++) {
                var item = g.items[j], after = { keys: copyKeys(item.before.keys) };
                for (k = 0; k < after.keys.length; k++) if (after.keys[k].selected) { after.keys[k].time += shift; moved++; }
                after.keys.sort(function (a, b) { return a.time - b.time; });
                for (k = 1; k < after.keys.length; k++) {
                    if (Math.abs(after.keys[k].time - after.keys[k - 1].time) < EPS) {
                        fail("Cancelled: a moved key would land on another key on " + g.layer.name + " > " + item.property.name + ".");
                    }
                }
                plans.push({ property: item.property, before: item.before, after: after });
            }
        }
        if (!plans.length) fail("The selected keys already start at each layer's " + (edge === "in" ? "in point." : "last frame."));
        applyPlans(edge === "in" ? "Keys to Layer In" : "Keys to Layer Out", plans);
        return moved;
    }
    // Every keyframe on the layer counts, selected or not. Layer markers are not keyframes.
    function keyBounds(layer) {
        var bounds = { first: Infinity, last: -Infinity };
        walk(layer, function (p) {
            if (p.matchName === "ADBE Marker" || !p.numKeys) return;
            for (var i = 1; i <= p.numKeys; i++) {
                bounds.first = Math.min(bounds.first, p.keyTime(i));
                bounds.last = Math.max(bounds.last, p.keyTime(i));
            }
        });
        return bounds;
    }
    function setLayerSpan(layer, inPoint, outPoint) {
        // Set the end that keeps in < out valid at every intermediate step.
        if (inPoint < layer.outPoint) { layer.inPoint = inPoint; layer.outPoint = outPoint; }
        else { layer.outPoint = outPoint; layer.inPoint = inPoint; }
    }
    // The layer starts on its first key and ends after the frame of its last key.
    function trimToKeys(c, mode) {
        if (mode !== "in" && mode !== "out" && mode !== "both") fail("Trim mode must be in, out or both.");
        var layers = selectedLayers(c), plans = [], noKeys = 0, i;
        for (i = 0; i < layers.length; i++) {
            var layer = layers[i];
            if (layer.locked) fail("Unlock layer: " + layer.name);
            var bounds = keyBounds(layer);
            if (!isFinite(bounds.first)) { noKeys++; continue; }
            var inPoint = mode === "out" ? layer.inPoint : Math.max(0, Math.min(bounds.first, c.duration));
            var outPoint = mode === "in" ? layer.outPoint : Math.max(0, Math.min(bounds.last + c.frameDuration, c.duration));
            if (outPoint - inPoint < c.frameDuration - EPS) fail(layer.name + ": its keys would leave less than one visible frame inside the layer and comp.");
            if (Math.abs(inPoint - layer.inPoint) < EPS && Math.abs(outPoint - layer.outPoint) < EPS) continue;
            plans.push({ layer: layer, inPoint: layer.inPoint, outPoint: layer.outPoint, newIn: inPoint, newOut: outPoint });
        }
        if (!plans.length) fail(noKeys === layers.length ? "The selected layers have no keyframes." : "The selected layers already match their keys.");
        undo("Trim Layers to Keys", function () {
            var done = 0;
            try {
                for (i = 0; i < plans.length; i++) {
                    var plan = plans[i];
                    done = i + 1;
                    setLayerSpan(plan.layer, plan.newIn, plan.newOut);
                    // Footage cannot extend past its source: After Effects may clamp instead of failing.
                    if (Math.abs(plan.layer.inPoint - plan.newIn) > EPS || Math.abs(plan.layer.outPoint - plan.newOut) > EPS) {
                        fail("Can't extend " + plan.layer.name + " beyond its footage. Trim that layer by hand.");
                    }
                }
            } catch (error) {
                var failures = [];
                for (var r = done - 1; r >= 0; r--) {
                    try { setLayerSpan(plans[r].layer, plans[r].inPoint, plans[r].outPoint); } catch (restoreError) { failures.push(restoreError.toString()); }
                }
                if (failures.length) fail(error.toString() + "\nRecovery incomplete. Use Undo immediately.\n" + failures.join("\n"));
                throw error;
            }
        });
        return { layers: plans.length, noKeys: noKeys };
    }
    function transformProperty(layer, name) { return layer.property("ADBE Transform Group").property(name); }
    function transformProperties(layer) {
        var result = [], position = transformProperty(layer, "ADBE Position"), i;
        if (position.dimensionsSeparated) {
            for (i = 0; i < (layer.threeDLayer ? 3 : 2); i++) result.push(position.getSeparationFollower(i));
        } else result.push(position);
        result.push(transformProperty(layer, "ADBE Scale"));
        result.push(transformProperty(layer, "ADBE Rotate Z"));
        if (layer.threeDLayer) {
            result.push(transformProperty(layer, "ADBE Orientation"));
            result.push(transformProperty(layer, "ADBE Rotate X"));
            result.push(transformProperty(layer, "ADBE Rotate Y"));
        }
        return result;
    }
    function uniqueName(c, base) {
        var name = base, suffix = 2;
        while (true) {
            var exists = false;
            for (var i = 1; i <= c.numLayers; i++) if (c.layer(i).name === name) { exists = true; break; }
            if (!exists) return name;
            name = base + " " + suffix++;
        }
    }
    function toNull(c) {
        var layers = selectedLayers(c);
        if (layers.length !== 1) fail("Select exactly one layer.");
        var source = layers[0];
        var isVisual = source instanceof AVLayer ||
            (typeof ShapeLayer !== "undefined" && source instanceof ShapeLayer) ||
            (typeof TextLayer !== "undefined" && source instanceof TextLayer);
        if (!isVisual || source.locked) fail("Select an unlocked AV, text or shape layer (not a camera/light).");
        if (source.autoOrient !== AutoOrientType.NO_AUTO_ORIENT) fail("Disable Auto-Orient first.");
        if (source.collapseTransformation && source.matchName !== "ADBE Vector Layer" && source.matchName !== "ADBE Text Layer") {
            fail("Collapsed precomps / continuously rasterized footage are not supported in this beta.");
        }
        // Hierarchy changes can alter arbitrary expressions, even disabled ones when re-enabled.
        walk(source, function (p) { if (hasExpression(p)) fail("Remove expressions on this layer first: " + p.name); });
        var props = transformProperties(source), snapshots = [], oldParent = source.parent;
        var nullName = uniqueName(c, "CTRL_" + source.name);
        for (var i = 0; i < props.length; i++) snapshots.push(snapshot(props[i]));
        return undo("Transform to Null", function () {
            var controller = null, controllerSource = null, sourceTouched = false, knownItems = {};
            for (var itemIndex = 1; itemIndex <= app.project.numItems; itemIndex++) knownItems["$" + app.project.item(itemIndex).id] = true;
            try {
                controller = c.layers.addNull(c.duration);
                if (!knownItems["$" + controller.source.id]) controllerSource = controller.source;
                controller.name = nullName;
                controller.threeDLayer = source.threeDLayer;
                controller.label = source.label;
                controller.startTime = source.startTime;
                controller.inPoint = source.inPoint;
                controller.outPoint = source.outPoint;
                controller.moveBefore(source);
                controller.setParentWithJump(oldParent);
                // Identity pivot: this is essential to avoid a positional jump.
                transformProperty(controller, "ADBE Anchor Point").setValue(source.threeDLayer ? [0, 0, 0] : [0, 0]);
                transformProperty(controller, "ADBE Position").dimensionsSeparated = transformProperty(source, "ADBE Position").dimensionsSeparated;
                var targets = transformProperties(controller);
                for (i = 0; i < targets.length; i++) { write(targets[i], snapshots[i]); verify(targets[i], snapshots[i]); }
                // Do not touch the source until EVERY channel on the controller verifies.
                sourceTouched = true;
                source.setParentWithJump(controller);
                for (i = 0; i < props.length; i++) {
                    var p = props[i], value = p.value, reset;
                    if (p.matchName === "ADBE Scale") reset = source.threeDLayer ? [100, 100, 100] : [100, 100];
                    else if (value instanceof Array) {
                        reset = [];
                        for (var d = 0; d < value.length; d++) reset.push(0);
                    } else reset = 0;
                    write(p, { keys: [], value: reset });
                }
                source.selected = false;
                controller.selected = true;
                return controller;
            } catch (error) {
                var failures = [];
                if (sourceTouched) {
                    try { source.setParentWithJump(oldParent); } catch (parentError) { failures.push(parentError.toString()); }
                    for (i = 0; i < snapshots.length; i++) {
                        try { write(props[i], snapshots[i]); } catch (restoreError) { failures.push(restoreError.toString()); }
                    }
                }
                if (!failures.length && controller) {
                    try { controller.remove(); } catch (removeError) { failures.push(removeError.toString()); }
                    if (!failures.length && controllerSource && controllerSource.usedIn.length === 0) {
                        try { controllerSource.remove(); } catch (solidError) { failures.push(solidError.toString()); }
                    }
                }
                source.selected = true;
                if (failures.length) fail(error.toString() + "\nRecovery incomplete. Use Undo immediately.\n" + failures.join("\n"));
                throw error;
            }
        });
    }
    return {
        comp: comp, run: run, space: space, step: step, toNull: toNull,
        keepEvery: keepEvery, keysToLayer: keysToLayer, trimToKeys: trimToKeys,
        frameInterval: frameInterval, walk: walk, hasExpression: hasExpression, undo: undo,
        snapshot: snapshot, write: write, verify: verify
    };
}());
// Dockable panel (ScriptUI Panels folder) or floating window (Run Script File).
// A KBar button can run one action directly by passing its name as the button argument.
var KeyframeTools = (function () {
    var SECTION = "PedroMafra.KeyframeTools", KEY = "options_v1";
    // One whole number N: frames for Space and Step, keys for Keep.
    function decode(value) {
        // v1 also stored options the panel no longer has; v3 had a frames/seconds unit (frames kept).
        var match = typeof value === "string" ? (/^v2\|([1-9][0-9]{0,4})$/.exec(value) || /^v3\|f\|([1-9][0-9]{0,4})$/.exec(value) ||
            /^v1\|([1-9][0-9]{0,4})\|[01]\|[01]\|[01]$/.exec(value)) : null;
        return { amount: match ? match[1] : "2" };
    }
    function readOptions() {
        try { return app.settings.haveSetting(SECTION, KEY) ? decode(app.settings.getSetting(SECTION, KEY)) : decode(null); }
        catch (e) { return decode(null); }
    }
    function saveOptions(options) {
        // Only a valid number is remembered; a bad entry still reaches the action and is refused there.
        if (!/^[1-9][0-9]{0,4}$/.test(String(options.amount))) return;
        try { app.settings.saveSetting(SECTION, KEY, "v2|" + options.amount); } catch (e) {}
    }
    var actions = {
        "space": function (c, o) { PedroAE.space(c, o.amount, false, false); },
        "step": function (c, o) { PedroAE.step(c, o.amount, false); },
        "keep": function (c, o) { PedroAE.keepEvery(c, o.amount); },
        "keys-in": function (c) { PedroAE.keysToLayer(c, "in"); },
        "keys-out": function (c) { PedroAE.keysToLayer(c, "out"); },
        "trim-in": function (c) { PedroAE.trimToKeys(c, "in"); },
        "trim-out": function (c) { PedroAE.trimToKeys(c, "out"); },
        "trim-both": function (c) { PedroAE.trimToKeys(c, "both"); }
    };
    function perform(name, options) {
        if (!actions.hasOwnProperty(name)) throw new Error("Unknown action: " + name + ". Use space, step, keep, keys-in, keys-out, trim-in, trim-out or trim-both.");
        actions[name](PedroAE.comp(), options);
    }

    // Icons live in a 100 x 60 box, like Pedro's Keys-to-in/out SVGs: a gray layer bar and key diamonds.
    // ["bar", x, y, w, h, tone] · ["key", cx, cy, radius, filled, tone?] · ["line", x1, y1, x2, y2, width, tone]
    var ICONS = {
        "space": [["line", 12, 50, 88, 50, 2, "icon"], ["line", 12, 44, 12, 56, 2, "icon"], ["line", 37, 46, 37, 54, 2, "icon"], ["line", 63, 46, 63, 54, 2, "icon"], ["line", 88, 44, 88, 56, 2, "icon"],
            ["key", 12, 26, 9, true], ["key", 37, 26, 9, true], ["key", 63, 26, 9, true], ["key", 88, 26, 9, true]],
        "step": [["key", 12, 30, 10, true], ["key", 37, 30, 8, false], ["key", 63, 30, 8, false], ["key", 88, 30, 10, true]],
        "keep": [["key", 10, 30, 9, true], ["key", 30, 30, 5, true, "dim"], ["key", 50, 30, 9, true], ["key", 70, 30, 5, true, "dim"], ["key", 90, 30, 9, true]],
        "keys-in": [["bar", 5, 10, 90, 10, "icon"], ["key", 15, 40, 10, true], ["key", 45, 40, 10, true]],
        "keys-out": [["bar", 5, 10, 90, 10, "icon"], ["key", 55, 40, 10, true], ["key", 85, 40, 10, true]],
        "trim-in": [["bar", 5, 10, 20, 10, "dim"], ["bar", 25, 10, 70, 10, "icon"], ["line", 25, 3, 25, 57, 3, "cut"], ["key", 25, 40, 10, true], ["key", 60, 40, 10, true]],
        "trim-out": [["bar", 5, 10, 70, 10, "icon"], ["bar", 75, 10, 20, 10, "dim"], ["line", 75, 3, 75, 57, 3, "cut"], ["key", 40, 40, 10, true], ["key", 75, 40, 10, true]],
        "trim-both": [["bar", 5, 10, 12, 10, "dim"], ["bar", 17, 10, 66, 10, "icon"], ["bar", 83, 10, 12, 10, "dim"], ["line", 17, 3, 17, 57, 3, "cut"], ["line", 83, 3, 83, 57, 3, "cut"], ["key", 17, 40, 10, true], ["key", 83, 40, 10, true]]
    };
    var TONES = { icon: [0.66, 0.66, 0.66, 1], dim: [0.32, 0.32, 0.32, 1], cut: [0.85, 0.85, 0.85, 1] };
    var TIPS = {
        "space": "Space: spaces the selected keys N frames apart",
        "step": "Step: adds keys every N frames between the selected keys",
        "keep": "Keep: keeps every Nth selected key and removes the ones between (the first and last stay)",
        "keys-in": "Keys to layer in: moves the selected keys so the first one sits on the layer's in point",
        "keys-out": "Keys to layer out: moves the selected keys so the last one sits on the layer's last frame",
        "trim-in": "Trim in: the layer starts on its first keyframe",
        "trim-out": "Trim out: the layer ends after its last keyframe",
        "trim-both": "Trim both: the layer spans from its first to its last keyframe"
    };
    function drawButton(button, shapes, state) {
        var g = button.graphics, w = button.size[0], h = button.size[1];
        var fill = state && state.leftButtonPressed ? 0.12 : (state && state.mouseOver ? 0.24 : 0.18);
        g.newPath(); g.rectPath(0, 0, w, h);
        g.fillPath(g.newBrush(g.BrushType.SOLID_COLOR, [fill, fill, fill, 1]));
        g.strokePath(g.newPen(g.PenType.SOLID_COLOR, [0.29, 0.29, 0.29, 1], 1));
        var scale = Math.min((w - 10) / 100, (h - 6) / 60), left = (w - 100 * scale) / 2, top = (h - 60 * scale) / 2;
        function x(v) { return left + v * scale; }
        function y(v) { return top + v * scale; }
        for (var i = 0; i < shapes.length; i++) {
            var s = shapes[i];
            g.newPath();
            if (s[0] === "bar") {
                g.rectPath(x(s[1]), y(s[2]), s[3] * scale, s[4] * scale);
                g.fillPath(g.newBrush(g.BrushType.SOLID_COLOR, TONES[s[5]]));
            } else if (s[0] === "key") {
                g.moveTo(x(s[1]), y(s[2] - s[3])); g.lineTo(x(s[1] + s[3]), y(s[2])); g.lineTo(x(s[1]), y(s[2] + s[3])); g.lineTo(x(s[1] - s[3]), y(s[2])); g.closePath();
                var tone = TONES[s[5] || "icon"];
                if (s[4]) g.fillPath(g.newBrush(g.BrushType.SOLID_COLOR, tone));
                else g.strokePath(g.newPen(g.PenType.SOLID_COLOR, tone, Math.max(1, 2.4 * scale)));
            } else {
                g.moveTo(x(s[1]), y(s[2])); g.lineTo(x(s[3]), y(s[4]));
                g.strokePath(g.newPen(g.PenType.SOLID_COLOR, TONES[s[6]], Math.max(1, s[5] * scale)));
            }
        }
    }
    function kbarArgument() {
        try { if (typeof kbar !== "undefined" && kbar && kbar.button && kbar.button.argument) return String(kbar.button.argument).replace(/^\s+|\s+$/g, "").toLowerCase(); }
        catch (e) {}
        return "";
    }
    var BUTTON = [48, 28], GAP = 4, MARGIN = 8;
    // Lays out equal tiles in the most columns that fit, but only in counts that fill every row:
    // 9 tiles become a column, a 3 x 3 square or a single row, never a row with one tile left over.
    function flow(count, width) {
        var fit = Math.max(1, Math.floor((width + GAP) / (BUTTON[0] + GAP))), columns = 1, places = [], c, i;
        for (c = 1; c <= count; c++) if (count % c === 0 && c <= fit) columns = c;
        var left = Math.max(0, (width - (columns * BUTTON[0] + (columns - 1) * GAP)) / 2);
        for (i = 0; i < count; i++) places.push([left + (i % columns) * (BUTTON[0] + GAP), Math.floor(i / columns) * (BUTTON[1] + GAP)]);
        return places;
    }
    function buildPanel(host) {
        var win = host instanceof Panel ? host : new Window("palette", "Keyframes", undefined, { resizeable: true });
        win.orientation = "column"; win.alignChildren = ["center", "top"]; win.spacing = GAP; win.margins = MARGIN;

        // The N field is one more tile in the grid, the same size as the buttons.
        var amount = win.add("edittext", undefined, readOptions().amount);
        amount.preferredSize = BUTTON; amount.justify = "center";
        // The default font looks tiny in a button-sized field.
        try { amount.graphics.font = ScriptUI.newFont(amount.graphics.font.name, ScriptUI.FontStyle.REGULAR, 16); } catch (e) {}
        amount.helpTip = "N: frames for Space and Step, keys for Keep";
        function options() { return { amount: amount.text }; }
        amount.onChange = function () { saveOptions(options()); };

        var order = ["space", "step", "keep", "keys-in", "keys-out", "trim-in", "trim-out", "trim-both"], controls = [amount];
        for (var i = 0; i < order.length; i++) (function (name) {
            var button = win.add("iconbutton", undefined, undefined, { style: "toolbutton" });
            button.preferredSize = BUTTON;
            button.helpTip = TIPS[name];
            button.onDraw = function (state) { drawButton(this, ICONS[name], state); };
            button.onClick = function () {
                var chosen = options();
                saveOptions(chosen);
                // Success shows in the timeline itself; only refusals interrupt.
                try { perform(name, chosen); } catch (error) { alert(error.toString(), "Keyframe Tools"); }
            };
            controls.push(button);
        })(order[i]);

        // Like Nudge, the tiles follow the panel's shape instead of a fixed column.
        function arrange() {
            var places = flow(controls.length, Math.max(BUTTON[0], win.size[0] - 2 * MARGIN));
            for (var c = 0; c < controls.length; c++) {
                controls[c].location = [MARGIN + places[c][0], MARGIN + places[c][1]];
                controls[c].size = BUTTON;
            }
        }
        win.onResizing = win.onResize = win.onShow = arrange;
        win.layout.layout(true);
        arrange();
        if (win instanceof Window) { win.center(); win.show(); }
        return win;
    }
    function start(host) {
        var argument = kbarArgument();
        if (argument) { PedroAE.run("Keyframe Tools", function () { perform(argument, readOptions()); }); return null; }
        return buildPanel(host);
    }
    return { start: start, perform: perform, decode: decode, icons: ICONS, drawButton: drawButton, flow: flow };
}());
KeyframeTools.start(thisObj);

}(this));
