// Stepped-Keyframes v0.2.0-beta.1 — Pedro Mafra
// MIT License. Standalone ExtendScript; generated by tools/build.js.
// Usage and limitations: https://github.com/pdrmafra/after-effects-scripts
(function () {
// Shared ES3-compatible source. Build embeds it in each standalone script.
var PedroAE = (function () {
    var EPS = 0.000001;

    function fail(message) { throw new Error(message); }
    function clone(value) {
        if (!(value instanceof Array)) return value;
        var result = [];
        for (var i = 0; i < value.length; i++) result.push(clone(value[i]));
        return result;
    }
    function equal(a, b) {
        if (typeof a === "number" && typeof b === "number") return Math.abs(a - b) < EPS;
        if (a instanceof Array && b instanceof Array) {
            if (a.length !== b.length) return false;
            for (var i = 0; i < a.length; i++) if (!equal(a[i], b[i])) return false;
            return true;
        }
        return a === b;
    }
    function comp() {
        var item = app.project && app.project.activeItem;
        if (!(item instanceof CompItem)) fail("Open a composition first.");
        return item;
    }
    function selectedLayers(c) {
        var layers = c.selectedLayers;
        if (!layers.length) fail("Select at least one layer.");
        return layers;
    }
    function undo(name, action) {
        app.beginUndoGroup(name);
        try { return action(); } finally { app.endUndoGroup(); }
    }
    function run(name, action) {
        try { action(); } catch (error) { alert(name + ":\n" + error.toString()); }
    }
    function walk(group, visit) {
        if (group.propertyType === PropertyType.PROPERTY) { visit(group); return; }
        for (var i = 1; i <= group.numProperties; i++) walk(group.property(i), visit);
    }
    function hasExpression(p) { return p.canSetExpression && p.expression !== ""; }
    function spatial(p) {
        return p.propertyValueType === PropertyValueType.TwoD_SPATIAL || p.propertyValueType === PropertyValueType.ThreeD_SPATIAL;
    }
    function supported(p) {
        var t = p.propertyValueType;
        return t === PropertyValueType.OneD || t === PropertyValueType.TwoD ||
            t === PropertyValueType.ThreeD || t === PropertyValueType.COLOR ||
            t === PropertyValueType.TwoD_SPATIAL || t === PropertyValueType.ThreeD_SPATIAL ||
            t === PropertyValueType.SHAPE || t === PropertyValueType.TEXT_DOCUMENT;
    }
    function easeData(ease) {
        var data = [];
        for (var i = 0; i < ease.length; i++) data.push([ease[i].speed, ease[i].influence]);
        return data;
    }
    function easeObjects(data) {
        var ease = [];
        for (var i = 0; i < data.length; i++) ease.push(new KeyframeEase(data[i][0], data[i][1]));
        return ease;
    }
    function snapshot(p) {
        var data = { property: p, keys: [] };
        if (!p.numKeys) { data.value = clone(p.value); return data; }
        for (var i = 1; i <= p.numKeys; i++) {
            var k = {
                time: p.keyTime(i), value: clone(p.keyValue(i)), selected: p.keySelected(i),
                inType: p.keyInInterpolationType(i), outType: p.keyOutInterpolationType(i),
                inEase: easeData(p.keyInTemporalEase(i)), outEase: easeData(p.keyOutTemporalEase(i)),
                continuous: p.keyTemporalContinuous(i), auto: p.keyTemporalAutoBezier(i)
            };
            if (spatial(p)) {
                k.inTangent = clone(p.keyInSpatialTangent(i));
                k.outTangent = clone(p.keyOutSpatialTangent(i));
                k.spatialContinuous = p.keySpatialContinuous(i);
                k.spatialAuto = p.keySpatialAutoBezier(i);
                k.roving = p.keyRoving(i);
            }
            // Keyframe labels were added in AE 22.6. Never suppress a failed copy.
            if (typeof p.keyLabel === "function") k.label = p.keyLabel(i);
            data.keys.push(k);
        }
        return data;
    }
    function clearKeys(p) { for (var i = p.numKeys; i >= 1; i--) p.removeKey(i); }
    function write(p, data) {
        var easing = [], supportsEase = p.isInterpolationTypeValid(KeyframeInterpolationType.BEZIER);
        // Source Text is HOLD-only and reports zero influence (invalid for KeyframeEase).
        // Prepare all valid ease objects before deleting any existing keys.
        for (var e = 0; e < data.keys.length; e++) {
            var original = data.keys[e];
            if (supportsEase && (original.inType !== KeyframeInterpolationType.HOLD || original.outType !== KeyframeInterpolationType.HOLD)) {
                easing[e] = [easeObjects(original.inEase), easeObjects(original.outEase)];
            }
        }
        clearKeys(p);
        if (!data.keys.length) { p.setValue(clone(data.value)); return; }
        var i, k;
        // Create the complete sequence before assigning neighbor-dependent flags.
        for (i = 0; i < data.keys.length; i++) {
            k = data.keys[i];
            var index = p.addKey(k.time);
            p.setValueAtKey(index, clone(k.value));
        }
        for (i = 0; i < data.keys.length; i++) {
            k = data.keys[i];
            p.setTemporalAutoBezierAtKey(i + 1, false);
            p.setTemporalContinuousAtKey(i + 1, false);
            if (easing[i]) p.setTemporalEaseAtKey(i + 1, easing[i][0], easing[i][1]);
            // Ease setters can change interpolation: restore interpolation AFTER ease.
            p.setInterpolationTypeAtKey(i + 1, k.inType, k.outType);
            if (spatial(p)) {
                p.setSpatialAutoBezierAtKey(i + 1, false);
                p.setSpatialContinuousAtKey(i + 1, false);
                p.setSpatialTangentsAtKey(i + 1, k.inTangent, k.outTangent);
                p.setSpatialContinuousAtKey(i + 1, k.spatialContinuous);
                p.setSpatialAutoBezierAtKey(i + 1, k.spatialAuto);
            }
            p.setTemporalContinuousAtKey(i + 1, k.continuous);
            p.setTemporalAutoBezierAtKey(i + 1, k.auto);
            if (k.label !== undefined) p.setLabelAtKey(i + 1, k.label);
            p.setSelectedAtKey(i + 1, k.selected);
        }
        if (spatial(p)) {
            for (i = 0; i < data.keys.length; i++) p.setRovingAtKey(i + 1, data.keys[i].roving);
        }
    }
    function verify(p, data) {
        var actual = snapshot(p);
        if (actual.keys.length !== data.keys.length) fail("Key count changed while copying " + p.name + ".");
        if (!data.keys.length) {
            if (!equal(actual.value, data.value)) fail("Static value copy failed: " + p.name);
            return;
        }
        for (var i = 0; i < data.keys.length; i++) {
            var expected = data.keys[i], copied = actual.keys[i];
            for (var field in expected) {
                if (expected.hasOwnProperty(field) && !equal(expected[field], copied[field])) {
                    fail("Key copy verification failed: " + p.name + " key " + (i + 1) + " / " + field);
                }
            }
        }
    }
    function restoreAll(plans, count, error) {
        var failures = [];
        for (var i = count - 1; i >= 0; i--) {
            try { write(plans[i].property, plans[i].before); }
            catch (restoreError) { failures.push(restoreError.toString()); }
        }
        if (failures.length) fail(error.toString() + "\nRecovery incomplete. Use Undo immediately.\n" + failures.join("\n"));
        throw error;
    }
    function keyProperties(c, allKeys) {
        var result = [], selected = c.selectedProperties;
        for (var i = 0; i < selected.length; i++) {
            walk(selected[i], function (p) {
                if (!p.numKeys || (!allKeys && (!p.selectedKeys || !p.selectedKeys.length))) return;
                for (var j = 0; j < result.length; j++) if (result[j] === p) return;
                var layer = p.propertyGroup(p.propertyDepth);
                if (layer.locked) fail("Unlock layer: " + layer.name);
                if (!supported(p)) fail("Unsupported property: " + p.name);
                if (hasExpression(p)) fail("Remove expressions first: " + p.name);
                var before = snapshot(p);
                for (j = 0; j < before.keys.length; j++) {
                    var k = before.keys[j];
                    if (k.roving || k.auto || k.continuous) {
                        fail("Disable roving / temporal auto-Bezier / temporal continuous first: " + p.name);
                    }
                }
                result.push(p);
            });
        }
        if (!result.length) fail("Select animated properties and keyframes first.");
        return result;
    }
    function frameInterval(value) {
        var number = Number(value);
        if (!isFinite(number) || number <= 0 || Math.floor(number) !== number) fail("Enter a positive whole number of frames.");
        return number;
    }
    function applyPlans(name, plans) {
        return undo(name, function () {
            var count = 0;
            try {
                for (var i = 0; i < plans.length; i++) {
                    count = i + 1;
                    write(plans[i].property, plans[i].after);
                }
            } catch (error) { restoreAll(plans, count, error); }
            return plans.length;
        });
    }
    function space(c, frames, atCurrentTime, allKeys) {
        frames = frameInterval(frames);
        var properties = keyProperties(c, allKeys), plans = [];
        for (var i = 0; i < properties.length; i++) {
            var p = properties[i], before = snapshot(p), after = { keys: [] }, chosen = [];
            for (var j = 0; j < before.keys.length; j++) {
                var key = {}, original = before.keys[j];
                for (var field in original) if (original.hasOwnProperty(field)) key[field] = original[field];
                after.keys.push(key);
                if (allKeys || key.selected) chosen.push(key);
            }
            if (!chosen.length || (chosen.length === 1 && !atCurrentTime)) continue;
            var start = atCurrentTime ? c.time : chosen[0].time;
            for (j = 0; j < chosen.length; j++) chosen[j].time = start + j * frames * c.frameDuration;
            after.keys.sort(function (a, b) { return a.time - b.time; });
            for (j = 1; j < after.keys.length; j++) {
                if (Math.abs(after.keys[j].time - after.keys[j - 1].time) < EPS) {
                    fail("Spacing cancelled: a key would overwrite another key on " + p.name + ".");
                }
            }
            plans.push({ property: p, before: before, after: after });
        }
        if (!plans.length) fail("Select at least two keys, or choose Current Time to move a single key.");
        return applyPlans("Spacing Keyframes", plans);
    }
    function sampledKey(p, time, value, hold) {
        var count = p.keyInTemporalEase(1).length, easing = [], i;
        for (i = 0; i < count; i++) easing.push([0, 33.333333]);
        var type = hold || !p.isInterpolationTypeValid(KeyframeInterpolationType.LINEAR) ? KeyframeInterpolationType.HOLD : KeyframeInterpolationType.LINEAR;
        var k = { time: time, value: clone(value), selected: true,
            inType: type, outType: type, inEase: easing, outEase: easing,
            continuous: false, auto: false };
        if (spatial(p)) {
            var tangent = [];
            for (i = 0; i < value.length; i++) tangent.push(0);
            k.inTangent = tangent; k.outTangent = clone(tangent);
            k.spatialContinuous = false; k.spatialAuto = false; k.roving = false;
        }
        if (typeof p.keyLabel === "function") k.label = 0;
        k.sample = true;
        return k;
    }
    // A spatial segment is the cubic Bezier value, value+outTangent, next+inTangent, next.
    // Splitting it at the samples (de Casteljau) keeps the original motion path. Without this,
    // the bounding keys keep handles sized for the whole segment and loop around close samples.
    function lerp(a, b, t) { var r = []; for (var i = 0; i < a.length; i++) r.push(a[i] + (b[i] - a[i]) * t); return r; }
    function offset(a, b, sign) { var r = []; for (var i = 0; i < a.length; i++) r.push(a[i] + sign * b[i]); return r; }
    function distance(a, b) { var s = 0; for (var i = 0; i < a.length; i++) s += (a[i] - b[i]) * (a[i] - b[i]); return Math.sqrt(s); }
    function split(c, u) {
        var a = lerp(c[0], c[1], u), b = lerp(c[1], c[2], u), d = lerp(c[2], c[3], u), e = lerp(a, b, u), f = lerp(b, d, u), m = lerp(e, f, u);
        return [[c[0], a, e, m], [m, f, d, c[3]]];
    }
    function curveParameter(c, point, from) {
        var best = from, bestDistance = Infinity, steps = 128, step = (1 - from) / steps, i, j, u, d;
        for (i = 0; i <= steps; i++) {
            u = from + i * step; d = distance(split(c, u)[0][3], point);
            if (d < bestDistance) { bestDistance = d; best = u; }
        }
        for (i = 0; i < 40; i++) {
            step /= 2;
            for (j = -1; j <= 1; j += 2) {
                u = Math.min(1, Math.max(from, best + j * step)); d = distance(split(c, u)[0][3], point);
                if (d < bestDistance) { bestDistance = d; best = u; }
            }
        }
        return { u: best, error: bestDistance };
    }
    function subdivideSpatial(keys) {
        for (var i = 0; i < keys.length; i++) {
            if (keys[i].sample) continue;
            var j = i + 1;
            while (j < keys.length && keys[j].sample) j++;
            if (j >= keys.length || j === i + 1 || keys[i].outType === KeyframeInterpolationType.HOLD) continue;
            var a = keys[i], b = keys[j], curve = [a.value, offset(a.value, a.outTangent, 1), offset(b.value, b.inTangent, 1), b.value];
            var tolerance = Math.max(0.01, 0.00001 * (distance(curve[0], curve[1]) + distance(curve[1], curve[2]) + distance(curve[2], curve[3])));
            var found = [], from = 0, s;
            for (s = i + 1; s < j; s++) {
                var hit = curveParameter(curve, keys[s].value, from);
                if (hit.error > tolerance) break;
                found.push(hit.u); from = hit.u;
            }
            // A sample off this curve is unexpected: keep straight sample handles, as before.
            if (found.length !== j - i - 1) continue;
            var rest = curve, start = 0, previous = a;
            for (s = 0; s < found.length; s++) {
                var parts = split(rest, start < 1 ? (found[s] - start) / (1 - start) : 0), sample = keys[i + 1 + s];
                previous.outTangent = offset(parts[0][1], parts[0][0], -1);
                sample.inTangent = offset(parts[0][2], parts[0][3], -1);
                sample.outTangent = offset(parts[1][1], parts[1][0], -1);
                sample.spatialContinuous = true;
                rest = parts[1]; start = found[s]; previous = sample;
            }
            b.inTangent = offset(rest[2], rest[3], -1);
        }
    }
    function step(c, frames, hold) {
        frames = frameInterval(frames);
        var properties = keyProperties(c, false), plans = [], total = 0;
        for (var i = 0; i < properties.length; i++) {
            var p = properties[i], before = snapshot(p), after = { keys: [] }, selected = [];
            for (var j = 0; j < before.keys.length; j++) {
                var key = {}, original = before.keys[j];
                for (var field in original) if (original.hasOwnProperty(field)) key[field] = original[field];
                after.keys.push(key);
                if (key.selected) selected.push(key.time);
            }
            if (selected.length < 2) continue;
            var added = 0;
            for (j = 0; j < selected.length - 1; j++) {
                var start = selected[j], end = selected[j + 1], interval = frames * c.frameDuration;
                // All values come from the untouched original curve, not inserted keys.
                for (var n = 1; start + n * interval < end - EPS; n++) {
                    var time = start + n * interval, exists = false;
                    for (var k = 0; k < before.keys.length; k++) {
                        if (Math.abs(before.keys[k].time - time) < EPS) { exists = true; break; }
                    }
                    if (exists) continue;
                    if (++total > 10000) fail("Cancelled: more than 10,000 new keys. Use a larger interval.");
                    after.keys.push(sampledKey(p, time, p.valueAtTime(time, true), hold));
                    added++;
                }
                if (hold) {
                    for (k = 0; k < after.keys.length; k++) {
                        if (after.keys[k].time >= start - EPS && after.keys[k].time < end - EPS) {
                            after.keys[k].inType = KeyframeInterpolationType.HOLD;
                            after.keys[k].outType = KeyframeInterpolationType.HOLD;
                        }
                    }
                }
            }
            if (!added && !hold) continue;
            after.keys.sort(function (a, b) { return a.time - b.time; });
            if (!hold && spatial(p)) subdivideSpatial(after.keys);
            for (j = 0; j < after.keys.length; j++) delete after.keys[j].sample;
            plans.push({ property: p, before: before, after: after });
        }
        if (!plans.length) fail("No samples to insert. Select at least two keys and check the interval.");
        applyPlans("Stepped Keyframes", plans);
        return total;
    }
    function transformProperty(layer, name) { return layer.property("ADBE Transform Group").property(name); }
    function transformProperties(layer) {
        var result = [], position = transformProperty(layer, "ADBE Position"), i;
        if (position.dimensionsSeparated) {
            for (i = 0; i < (layer.threeDLayer ? 3 : 2); i++) result.push(position.getSeparationFollower(i));
        } else result.push(position);
        result.push(transformProperty(layer, "ADBE Scale"));
        result.push(transformProperty(layer, "ADBE Rotate Z"));
        if (layer.threeDLayer) {
            result.push(transformProperty(layer, "ADBE Orientation"));
            result.push(transformProperty(layer, "ADBE Rotate X"));
            result.push(transformProperty(layer, "ADBE Rotate Y"));
        }
        return result;
    }
    function uniqueName(c, base) {
        var name = base, suffix = 2;
        while (true) {
            var exists = false;
            for (var i = 1; i <= c.numLayers; i++) if (c.layer(i).name === name) { exists = true; break; }
            if (!exists) return name;
            name = base + " " + suffix++;
        }
    }
    function toNull(c) {
        var layers = selectedLayers(c);
        if (layers.length !== 1) fail("Select exactly one layer.");
        var source = layers[0];
        var isVisual = source instanceof AVLayer ||
            (typeof ShapeLayer !== "undefined" && source instanceof ShapeLayer) ||
            (typeof TextLayer !== "undefined" && source instanceof TextLayer);
        if (!isVisual || source.locked) fail("Select an unlocked AV, text or shape layer (not a camera/light).");
        if (source.autoOrient !== AutoOrientType.NO_AUTO_ORIENT) fail("Disable Auto-Orient first.");
        if (source.collapseTransformation && source.matchName !== "ADBE Vector Layer" && source.matchName !== "ADBE Text Layer") {
            fail("Collapsed precomps / continuously rasterized footage are not supported in this beta.");
        }
        // Hierarchy changes can alter arbitrary expressions, even disabled ones when re-enabled.
        walk(source, function (p) { if (hasExpression(p)) fail("Remove expressions on this layer first: " + p.name); });
        var props = transformProperties(source), snapshots = [], oldParent = source.parent;
        var nullName = uniqueName(c, "CTRL_" + source.name);
        for (var i = 0; i < props.length; i++) snapshots.push(snapshot(props[i]));
        return undo("Transform to Null", function () {
            var controller = null, controllerSource = null, sourceTouched = false, knownItems = {};
            for (var itemIndex = 1; itemIndex <= app.project.numItems; itemIndex++) knownItems["$" + app.project.item(itemIndex).id] = true;
            try {
                controller = c.layers.addNull(c.duration);
                if (!knownItems["$" + controller.source.id]) controllerSource = controller.source;
                controller.name = nullName;
                controller.threeDLayer = source.threeDLayer;
                controller.label = source.label;
                controller.startTime = source.startTime;
                controller.inPoint = source.inPoint;
                controller.outPoint = source.outPoint;
                controller.moveBefore(source);
                controller.setParentWithJump(oldParent);
                // Identity pivot: this is essential to avoid a positional jump.
                transformProperty(controller, "ADBE Anchor Point").setValue(source.threeDLayer ? [0, 0, 0] : [0, 0]);
                transformProperty(controller, "ADBE Position").dimensionsSeparated = transformProperty(source, "ADBE Position").dimensionsSeparated;
                var targets = transformProperties(controller);
                for (i = 0; i < targets.length; i++) { write(targets[i], snapshots[i]); verify(targets[i], snapshots[i]); }
                // Do not touch the source until EVERY channel on the controller verifies.
                sourceTouched = true;
                source.setParentWithJump(controller);
                for (i = 0; i < props.length; i++) {
                    var p = props[i], value = p.value, reset;
                    if (p.matchName === "ADBE Scale") reset = source.threeDLayer ? [100, 100, 100] : [100, 100];
                    else if (value instanceof Array) {
                        reset = [];
                        for (var d = 0; d < value.length; d++) reset.push(0);
                    } else reset = 0;
                    write(p, { keys: [], value: reset });
                }
                source.selected = false;
                controller.selected = true;
                return controller;
            } catch (error) {
                var failures = [];
                if (sourceTouched) {
                    try { source.setParentWithJump(oldParent); } catch (parentError) { failures.push(parentError.toString()); }
                    for (i = 0; i < snapshots.length; i++) {
                        try { write(props[i], snapshots[i]); } catch (restoreError) { failures.push(restoreError.toString()); }
                    }
                }
                if (!failures.length && controller) {
                    try { controller.remove(); } catch (removeError) { failures.push(removeError.toString()); }
                    if (!failures.length && controllerSource && controllerSource.usedIn.length === 0) {
                        try { controllerSource.remove(); } catch (solidError) { failures.push(solidError.toString()); }
                    }
                }
                source.selected = true;
                if (failures.length) fail(error.toString() + "\nRecovery incomplete. Use Undo immediately.\n" + failures.join("\n"));
                throw error;
            }
        });
    }
    return {
        comp: comp, run: run, space: space, step: step, toNull: toNull,
        frameInterval: frameInterval, walk: walk, hasExpression: hasExpression, undo: undo,
        snapshot: snapshot, write: write, verify: verify
    };
}());
PedroAE.run("Stepped Keyframes", function () {
    var comp = PedroAE.comp();
    var win = new Window("dialog", "Stepped Keyframes");
    win.orientation = "column";
    win.alignChildren = ["fill", "top"];
    var row = win.add("group");
    row.add("statictext", undefined, "Sample interval (whole frames):");
    var input = row.add("edittext", undefined, "2");
    input.characters = 6;
    var hold = win.add("checkbox", undefined, "Hold between samples (changes interpolation inside chosen intervals)");
    win.add("statictext", undefined, "Select two or more keys. Existing keys are kept; values are sampled before any changes.");
    var buttons = win.add("group");
    var apply = buttons.add("button", undefined, "Apply");
    buttons.add("button", undefined, "Cancel", { name: "cancel" });
    apply.onClick = function () {
        try { PedroAE.step(comp, input.text, hold.value); win.close(1); }
        catch (error) { alert(error.toString()); }
    };
    win.center();
    win.show();
});

}());
