"use strict";
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const root = path.resolve(__dirname, "..");
const version = require("../package.json").version;
const entries = [
  ["Transform-to-Null", "transform-to-null"],
  ["Spacing-Keyframes", "spacing-keyframes"],
  ["Stepped-Keyframes", "stepped-keyframes"],
  ["Font-Inspector", "font-inspector"]
];
const check = process.argv.includes("--check");
for (const [name, source] of entries) {
  const shared = source === "font-inspector" ? "" : fs.readFileSync(path.join(root, "src/core.jsxinc"), "utf8");
  const entry = fs.readFileSync(path.join(root, `src/${source}.jsxinc`), "utf8");
  const built = `// ${name} v${version} — Pedro Mafra\n// MIT License. Standalone ExtendScript; generated by tools/build.js.\n// Usage and limitations: https://github.com/pdrmafra/after-effects-scripts\n(function () {\n${shared}${entry}\n}());\n`;
  new vm.Script(built, { filename: name });
  const target = path.join(root, `scripts/${name}.jsx`);
  if (check) {
    if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== built) throw new Error(`Stale build: ${name}. Run npm run build.`);
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, built);
  }
  console.log(`${check ? "Checked" : "Built"} ${name}`);
}
